#!/bin/bash
# Script para ejecutar migraciones en Render

echo "🚀 Ejecutando migraciones en Render..."
echo ""
echo "⚠️  IMPORTANTE: Este script requiere acceso SSH a Render"
echo ""
echo "Opciones:"
echo "1. Via Render Dashboard:"
echo "   - Ir a https://dashboard.render.com/web/srv-your-service-id"
echo "   - Click en 'Shell'"
echo "   - Ejecutar: python manage.py migrate"
echo ""
echo "2. Via Render CLI:"
echo "   - Instalar: npm install -g render-cli"
echo "   - Login: render login"
echo "   - Shell: render shell evalai2"
echo "   - Ejecutar: python manage.py migrate"
echo ""
echo "3. Trigger via API (si tienes endpoint custom):"
echo "   - curl -X POST https://evalai2.onrender.com/api/admin/migrate/"
echo ""
echo "✅ Migración a ejecutar: 0004_add_student_indexes"
echo ""
