# Generated by Django 5.2.7 on 2025-10-14 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rubric_ai_confidence_rubric_ai_generated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='ai_confidence',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='ai_generated',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='ai_model',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='ai_prompt_hash',
        ),
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Asignatura relacionada (opcional para comentarios generales)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='core.subject'),
        ),
        migrations.AddField(
            model_name='rubricscore',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Asignatura donde se realizó la evaluación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubric_scores', to='core.subject'),
        ),
    ]
