# Generated by Django 5.2.7 on 2025-10-14 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_rubric_ai_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.ForeignKey(
                blank=True,
                help_text='Asignatura relacionada (opcional para comentarios generales)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='comments',
                to='core.subject'
            ),
        ),
        migrations.AddField(
            model_name='rubricscore',
            name='subject',
            field=models.ForeignKey(
                blank=True,
                help_text='Asignatura donde se realizó la evaluación',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='rubric_scores',
                to='core.subject'
            ),
        ),
    ]
