# Generated by Django 5.2.7 on 2025-10-14 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_subject_to_comments_and_scores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha del registro de asistencia')),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('tarde', 'Tarde')], help_text='Estado de asistencia: presente, ausente o tarde', max_length=10)),
                ('comment', models.TextField(blank=True, help_text='Comentario opcional sobre la asistencia', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(help_text='Usuario que registró la asistencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Estudiante al que se registra la asistencia', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.student')),
                ('subject', models.ForeignKey(help_text='Asignatura en la que se toma asistencia', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.subject')),
            ],
            options={
                'ordering': ['-date', 'student__name'],
                'indexes': [models.Index(fields=['date', 'subject'], name='core_attend_date_a805a6_idx'), models.Index(fields=['student', 'date'], name='core_attend_student_931c39_idx')],
                'unique_together': {('student', 'subject', 'date')},
            },
        ),
    ]
