# Generated by Django 4.2.7 on 2025-11-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Nombre a mostrar en la UI', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='settings',
            field=models.TextField(blank=True, default='{}', help_text='JSON con configuraciones del usuario'),
        ),
    ]
