# Generated by Django 5.2.7 on 2025-10-15 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_evidence_objective_selfevaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la notificación', max_length=200)),
                ('message', models.TextField(help_text='Contenido de la notificación')),
                ('notification_type', models.CharField(choices=[('objective_reminder', 'Recordatorio de Objetivo'), ('evaluation_alert', 'Alerta de Evaluación'), ('system_alert', 'Alerta del Sistema'), ('achievement', 'Logro Desbloqueado')], default='system_alert', help_text='Tipo de notificación', max_length=50)),
                ('is_read', models.BooleanField(default=False, help_text='Si la notificación ha sido leída')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Fecha programada para enviar la notificación', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Fecha cuando se envió', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(help_text='Usuario que recibe la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_objective', models.ForeignKey(blank=True, help_text='Objetivo relacionado (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.objective')),
                ('related_student', models.ForeignKey(blank=True, help_text='Estudiante relacionado (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_notifications', to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='core_notifi_recipie_aeffaf_idx'), models.Index(fields=['scheduled_at'], name='core_notifi_schedul_340655_idx'), models.Index(fields=['notification_type'], name='core_notifi_notific_cbfe88_idx')],
            },
        ),
    ]
