# Generated by Django 5.2.7 on 2025-10-17 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubriccriterion',
            name='weight',
            field=models.FloatField(default=25.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
