# Generated by Django 5.2.7 on 2025-10-18 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_update_rubric_weight_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo de la corrección', max_length=200)),
                ('original_text', models.TextField(help_text='Texto original del estudiante')),
                ('corrected_text', models.TextField(help_text='Texto después de la corrección')),
                ('correction_type', models.CharField(choices=[('texto', 'Corrección de Texto'), ('ocr', 'Corrección OCR'), ('mixto', 'Corrección Mixta')], default='texto', help_text='Tipo de corrección realizada', max_length=20)),
                ('language_tool_matches', models.JSONField(default=list, help_text='Errores detectados por LanguageTool')),
                ('ocr_info', models.JSONField(blank=True, default=dict, help_text='Información del OCR si aplica', null=True)),
                ('statistics', models.JSONField(default=dict, help_text='Estadísticas del texto (palabras, caracteres, etc.)')),
                ('original_image', models.FileField(blank=True, help_text='Imagen original si es corrección OCR', null=True, upload_to='corrections/images/')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('revisada', 'Revisada'), ('aprobada', 'Aprobada'), ('necesita_mejora', 'Necesita Mejora')], default='pendiente', help_text='Estado actual de la corrección', max_length=20)),
                ('teacher_feedback', models.TextField(blank=True, help_text='Comentarios adicionales del profesor')),
                ('student_response', models.TextField(blank=True, help_text='Respuesta del estudiante a la corrección')),
                ('error_count', models.PositiveIntegerField(default=0, help_text='Número de errores encontrados')),
                ('correction_score', models.FloatField(blank=True, help_text='Puntuación de calidad de la corrección (0-10)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(help_text='Estudiante al que pertenece la corrección', on_delete=django.db.models.deletion.CASCADE, related_name='correction_evidences', to='core.student')),
                ('subject', models.ForeignKey(blank=True, help_text='Asignatura relacionada (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correction_evidences', to='core.subject')),
                ('teacher', models.ForeignKey(help_text='Profesor que realizó la corrección', on_delete=django.db.models.deletion.CASCADE, related_name='correction_evidences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidencia de Corrección',
                'verbose_name_plural': 'Evidencias de Corrección',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'created_at'], name='core_correc_student_16cb83_idx'), models.Index(fields=['teacher', 'created_at'], name='core_correc_teacher_cee324_idx'), models.Index(fields=['correction_type'], name='core_correc_correct_16191b_idx'), models.Index(fields=['status'], name='core_correc_status_ad492e_idx')],
            },
        ),
    ]
