# Generated by Django 4.2.7 on 2025-10-21 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_correctionevidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mostrado', models.CharField(blank=True, max_length=200)),
                ('centro_educativo', models.CharField(blank=True, max_length=300)),
                ('curso_periodo', models.CharField(blank=True, default='2024-2025', max_length=100)),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('ca', 'Català'), ('en', 'English'), ('fr', 'Français')], default='es', max_length=10)),
                ('tema', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('system', 'Sistema')], default='light', max_length=20)),
                ('tamano_fuente', models.CharField(choices=[('small', 'Pequeña'), ('medium', 'Media'), ('large', 'Grande')], default='medium', max_length=20)),
                ('escala_ui', models.IntegerField(default=100)),
                ('color_principal', models.CharField(default='#4f46e5', max_length=7)),
                ('notif_email', models.BooleanField(default=True)),
                ('notif_in_app', models.BooleanField(default=True)),
                ('recordatorio_minutos', models.IntegerField(choices=[(5, '5 minutos'), (15, '15 minutos'), (30, '30 minutos'), (60, '1 hora')], default=15)),
                ('notif_evaluaciones_pendientes', models.BooleanField(default=True)),
                ('notif_informes_listos', models.BooleanField(default=True)),
                ('notif_asistencias', models.BooleanField(default=True)),
                ('auto_logout_minutos', models.IntegerField(choices=[(15, '15 minutos'), (30, '30 minutos'), (60, '1 hora')], default=30)),
                ('cifrar_datos', models.BooleanField(default=False)),
                ('consentimiento_ia', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Usuario',
                'verbose_name_plural': 'Configuraciones de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='CustomEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('no_lectivo', 'Día no lectivo'), ('reminder', 'Recordatorio'), ('meeting', 'Reunión')], default='normal', max_length=20)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('todo_el_dia', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento Personalizado',
                'verbose_name_plural': 'Eventos Personalizados',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
    ]
