# Generated by Django 4.2.7 on 2025-10-21 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_user_settings_and_custom_events'),
    ]

    operations = [
    ]
